steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/responsive-sun-435918-p6/akashdeep-100946308/akashdeep-image:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/responsive-sun-435918-p6/akashdeep-100946308/akashdeep-image:$COMMIT_SHA']

options:
  logging: REGIONAL_USER_OWNED_BUCKET

